apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-ui
spec: 
  selector:
    matchLabels:
      app: demo-ui
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - name: demo-ui
        image: zsheaman/web-server-image:v1.0.0
        env: 
        - name: API_SERVER
          value: "http://demo-api-service:8082"
        ports:
        - containerPort: 8080
            
